# Generated by Django 4.1.7 on 2023-05-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcompany',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
